# basic options
title: Yuanyuan Tian
author: Yuanyuan Tian
description: Yuanyuan Tian — Partner Scientist Manager & Graph Architect at Microsoft

# Build settings
markdown: kramdown
exclude:
  - README.md
