# basic options
title: Yuanyuan Tian's Home Page
author: Yuanyuan Tian
#email: yuanyuan.t@gmail.com
description: The home page of Dr. Yuanyuan Tian
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
